### ISSUE TITLE
Assignments added late at night end up due the day before intended

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#12]
The client should not call `toUTC` on the date before sending to server. To reproduce this bug, set your clock to sometime between 12am and 4am then try to create a new assignment.

**Comment by calebsander** [comment]
Yeah, should probably test all of this more thoroughly. I have already had to deal with several issues resulting from UTC/local timezone synchronization. It's further complicated by the fact that the client and server aren't necessarily in the same timezone and that Sequelize turns `DATE` columns into `Date` objects representing the start of the day in UTC. Can't remember if dates in Sequelize queries have UTC time extracted or local time extracted.
