### ISSUE TITLE
Ideally, "load all conflicts" only considers present & future, not past

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#17]

**Comment by calebsander** [comment]
Sure, should be simple enough to change. Just have to change the start date in the query.

**Comment by calebsander** [comment]
Okay, this was actually a little more tricky than I thought. The fix is sort of approximate: if the maximum limit window is 3 days, it will display any limits violated by assignments that are due at most 2 days before the current date.

**Comment by calebsander** [comment]
Never mind, got it working as intended
