### ISSUE TITLE
Assignment button shows up for all groups, editable or not, but adds to "All students"

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#18]
EDIT: I thought editable because you can click "new assignment," but it actually just adds to "All students" group. So the bug is actually: the new assignment button shows up even if the hovered group is not editable, and clicking it adds an assignment to "all students."

original comment:
Not sure when this happened (or if it was my fault...), but it looks like I can now add assignments to other teachers' classes? This isn't ideal, but it's not too big a problem either. If you can figure out where this regression came in, it'd be good to fix.

**Comment by alex-lew** [comment]
I thought editable because you can click "new assignment," but it actually just adds to "All students" group. So the bug is actually: the new assignment button shows up even if the hovered group is not editable, and clicking it adds an assignment to "all students."

**Comment by calebsander** [comment]
Yeah, I'm in the process of fixing it. I used to not show the edit button when there weren't edit privileges, but you changed that so that the table wouldn't resize all the time.

**Comment by alex-lew** [comment]
I thought I made sure it didn't show when hoveredGroup wasn't set to the
current group, which should never happen if editing is not allowed? But no
worries! Thanks for working to fix.

**Comment by calebsander** [comment]
Yeah, may have come in when I refactored it

**Comment by calebsander** [comment]
Fixed with d02535de8b6d01ad57586a425bc09db312d10f22
