### ISSUE TITLE
AssignmentView draws incorrectly on Chrome (Mac OS, at least)

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#19]
Starting in d42219e60a6f1a961d702a27b0b099b275e3215e (I think), Chrome on macOS fails to redraw the calendar grid (particularly the borders in the table) correctly when assignments and infos are loaded. Resizing the window causes the page to redraw (correctly), and I don't see this bug in other browsers (Firefox and Safari). The advisor view also messes up sometimes, but usually less noticeably.

Screenshots:
<img width="1311" alt="screen shot 2017-08-24 at 5 23 40 pm" src="https://user-images.githubusercontent.com/1448179/29689409-1bc29bbe-88f1-11e7-9685-06d723a5dedb.png">
<img width="1323" alt="screen shot 2017-08-24 at 5 23 18 pm" src="https://user-images.githubusercontent.com/1448179/29689412-1f70dffa-88f1-11e7-811e-b3bebb6ce524.png">
<img width="1323" alt="screen shot 2017-08-24 at 5 22 48 pm" src="https://user-images.githubusercontent.com/1448179/29689417-2283f664-88f1-11e7-868d-176aee1508c3.png">
<img width="1314" alt="screen shot 2017-08-24 at 5 21 53 pm" src="https://user-images.githubusercontent.com/1448179/29689422-252e25f6-88f1-11e7-9860-c9b5ab3409fa.png">
<img width="1314" alt="screen shot 2017-08-24 at 5 22 28 pm" src="https://user-images.githubusercontent.com/1448179/29689425-28e8293a-88f1-11e7-9c25-c766b905e52b.png">

I am not sure what caused this, but there must be some difference in the CSS (?) between these two commits -- I didn't spot anything at first glance though.

Can you reproduce the bug? If so, if you can figure it out, that would be great! Otherwise I'll have some time tomorrow morning and can try to nail it down then.

**Comment by calebsander** [comment]
No, it's been working for me in Chrome on Ubuntu and Windows. No idea what causes that.

**Comment by alex-lew** [comment]
Really strange. OK, I can try to figure it out tomorrow.

**Comment by alex-lew** [comment]
This is going to sound ridiculous, but changing the spinner to use `v-if` solves the problem for me.  I have a hunch that this has to do with the fact that `loading = false` is always the last thing you do after updating some internal data; Vue calculates what depends on `loading` and in your current code, just sees that the style element of something or other needs to change, which doesn't trigger the same redrawing process that an actual element removal does.

Thoughts? Are you OK with my moving the spinner back to an absolute position in the corner so that the buttons don't move aside when loading? I can try to find a way to use v-if and keep it where it is as well.

**Comment by calebsander** [comment]
I doubt it is an issue with Vue, but rather with Chrome. But sure, if that fixes it for you, by all means go ahead.
