### ISSUE TITLE
Include date of window in limit violations list for admins

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#20]
Would be great if we could see when the assignments were! Perhaps this can replace "days in window" -- include a date range like 9/1 – 9/3.

**Comment by calebsander** [comment]
This wasn't a problem before you removed the dates from the assignment names :) https://github.com/calebsander/rjjenda/commit/e93d23e28c0e1e122ac498369379661a6cf91007#diff-0ff6ea54f4f4b215948a8a05ace2dc9dL31

**Comment by alex-lew** [comment]
Agreed -- sorry about that! I still think it's good not to have the clutter, so a solution that's not just to revert that change would be ideal. 

The ideal interface, I think, would be to replace "Days in window" with "Date" and display the date range, then for multi-day ranges have the assignment names end with (9/1) or (9/2), etc. The violations should be sorted by date (are they already?).

**Comment by calebsander** [comment]
Sure, makes sense. I'll work on that tonight. Don't think I was sorting the violations, but that would be easy too.
