### ISSUE TITLE
Bigger feature request: Events

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#22]
(At the meeting today, Ms. Budding & Ms. Jackman had a couple larger feature requests; I'm writing them up as issues but we can discuss whether it makes sense for you to implement.)

The current solution for all-school events, adding minor assignments to "All students," has a few downsides:

1. In the advisor view, the event shows up once for every student.
2. The word "minor" appears in the name of the event.
3. Since everyone has edit access, it's easy for a teacher to accidentally delete an event.
4. For people who do want it, "All students" is no longer a working group with warnings displayed. (You mentioned that it was still possible to add "All students" directly and have warnings display, but that doesn't work for me.)

Ultimately, I think we want an Events table rather than to keep adding special-case logic to the All-students group. However, we don't need to support adding/editing/deleting events from within the interface -- we can just put them in the database. So the idea would be to:
1. Create an events table, and an API for retrieving events for the week.
2. Create a row on top of the AssignmentsView that showed events.
No need for an interface for adding and removing individual events -- we can do that directly in the database using Postico.

**Comment by calebsander** [comment]
Yeah, I prevented listing groups twice in the `AssignmentsView`, so that's why the "add 'All students' manually" trick doesn't work anymore. You can still do it by adding specific grade groups. But sure, it should be easy to add an events table.

**Comment by alex-lew** [comment]
Sounds good. Will you have time to work on this today? If not, I'm happy to look into it. Faculty meetings start tomorrow, so I want to have a final-ish version deployed by then. Thanks!

**Comment by calebsander** [comment]
Yes, I have a few hours free now to work on this

**Comment by alex-lew** [comment]
Great, thank you!

**Comment by calebsander** [comment]
Do the events need any data besides name and date?

**Comment by alex-lew** [comment]
Nope!
