### ISSUE TITLE
Big feature request: Tracking resolutions of violations

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#24]
(At the meeting today, Ms. Budding & Ms. Jackman had a couple larger feature requests; I'm writing them up as issues but we can discuss whether it makes sense for you to implement.)

This is a big one, that wasn't part of the initial spec, so feel free to leave it be. Putting an issue here as documentation from the meeting.

The idea is that it would be nice to record the resolution to a limit violation (as a comment) and make this visible to all interested parties (including admin on the "limit violations" list). For example, I might write, "Caleb has an extension on this project, so will not have three things due the same day after all."

This is difficult, of course, because limit violations are calculated and not stored. I think what you'd need to do is:
1. Create a table for "resolutions," with columns for assignment ID, for student ID, and for comment.
2. If a student/assignment pair appears in the table, the assignment doesn't count toward limit violations for the student.
3. The comment appears in a tooltip on the assignment in the student and advisor view; maybe the assignment appears in a different color.
4. In the admin and teacher views, we could just have a separate list of resolutions.

**Comment by calebsander** [comment]
Yeah, I don't especially want to take this on. You're welcome to implement it yourself if you think it's important.
