### ISSUE TITLE
Calculating future dates (e.g. next week) sometimes fails due to Daylight Savings Time

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#29]
At least, I think it's due to Daylight Savings Time. If the current time is, say, 12:30am, then if you continually add exactly 7 days to the date, this will eventually leave you at 11:30pm on the day *prior* to the Monday you want, rather 12:30am on the Monday you want.

Is there a way to actually do arithmetic *on the date* instead of the date & time? Or can we normalize all times to something like noon or 2pm?

Not a huge deal, but this does mean that the app breaks every night between 12am and 1am...

**Comment by calebsander** [comment]
Without using a monolithic library like `moment`, I don't think it's very easy to know what the next day (or 7 days in the future) is. The JavaScript `Date` constructor either needs an epoch timestamp (which I was calculating by adding `7 * 24 * 60 * 60 * 1000` milliseconds) or a specific year, month, and day. I think the easiest (albeit a bit hacky) solution is probably to set the time to noon of the current date.

**Comment by calebsander** [comment]
Pushed what should hopefully fix this to another branch (see above). I can't test it right now because I'm at work, but you're welcome to merge it into master if it works.
