### ISSUE TITLE
check-limits prevents adding assignments when no limits are in place

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#31]
Edit: this only occurs when no limits are in place, so I think it's OK (we won't need to fix it).

Hi Caleb,

Using the updated code, any time I try to add an assignment, I get the error

Error occurred: invalid input syntax for type date: "Invalid date"

in an alert. I've investigated a bit and it seems that

- the error occurs in check-limits
- because the dates being passed in are not valid
- because adding maxDays to start (or -maxDays) produces an invalid date
- because maxDays is -Infinity

Will continue to investigate...

Ah! It might be because there are no limits...

**Comment by calebsander** [comment]
Whoops, this was in the original version too. Guess I never tested it with no limits. Should be fixed now.
