### ISSUE TITLE
Make assignments-view group hide button say "hide" so it is clearer what it does

### ISSUE THREAD

**Issue by alex-lew** [calebsander/rjjenda#7]
It looks like you've added a button for teachers to remove themselves from a section. Let's leave that to admins -- I can imagine teachers deleting something by mistake.

**Comment by calebsander** [comment]
Don't think that's the case. You mean on the assignments view? That just removes the group from the list of displayed groups. If you refresh the page, it will show up again.

**Comment by alex-lew** [comment]
Ah, sorry, I misunderstood what it did. In that case I’m not sure it’s necessary? An “x” button looks like “remove” / “delete” — if you want to keep it, maybe just make it a text button that says “HIDE”?

**Comment by calebsander** [comment]
Sure, I'll change that
